"""remove image

Revision ID: 0e1cdca7ea38
Revises: 69c82ba0ca7d
Create Date: 2022-05-14 20:25:15.846700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1cdca7ea38'
down_revision = '69c82ba0ca7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('image', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
