"""blog table change

Revision ID: 1bf9ff2cf0b8
Revises: cbf004245ff3
Create Date: 2022-05-15 00:44:03.496635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf9ff2cf0b8'
down_revision = 'cbf004245ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('sub_title', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=300), nullable=True),
    sa.Column('time_posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
