"""blog table change

Revision ID: 3143ec124138
Revises: d28a86110db3
Create Date: 2022-05-14 23:56:25.958449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3143ec124138'
down_revision = 'd28a86110db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('blog', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('blog', 'sub_title',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('blog', 'content',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.drop_column('blog', 'Timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('Timestamp', sa.DATETIME(), nullable=True))
    op.alter_column('blog', 'content',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('blog', 'sub_title',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('blog', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('blog', 'timestamp')
    # ### end Alembic commands ###
