"""remove image

Revision ID: 69c82ba0ca7d
Revises: f2e3506f564f
Create Date: 2022-05-14 20:24:07.021838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c82ba0ca7d'
down_revision = 'f2e3506f564f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('image', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
