"""add one to many relationship

Revision ID: cc46ddd0d5c7
Revises: d3f918ca1fb6
Create Date: 2022-05-14 11:43:18.013423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc46ddd0d5c7'
down_revision = 'd3f918ca1fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'user_id')
    # ### end Alembic commands ###
